# Generated by Django 5.1.7 on 2025-03-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_app', '0003_enrollment_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='intervention_app.enrollment'),
        ),
    ]
