# Generated by Django 5.1.7 on 2025-04-02 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_app', '0004_alter_intervention_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date_of_enrollment',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
